// ignore_for_file: non_constant_identifier_names, prefer_const_constructors

import 'package:flutter/material.dart';
import '../constant.dart';
import '../Pages/dashboard.dart';

List Accounts = [
  AccountCard(
    accountName: 'Esewasssssssssss',
    amount: "00000",
    borderColor: kMainBoxBorderColor,
    boxShadowColor: kBoxShadowMainBoxBolor,
    cardDetail: "CURRENT BALANCE",
    color: kBackgroundColorCard,
    iconBgColor: Colors.white,
    icons: Icon(Icons.account_balance),
  ),
  AccountCard(
    accountName: 'Khalti',
    amount: "00000",
    borderColor: kMainBoxBorderColor,
    boxShadowColor: kBoxShadowMainBoxBolor,
    cardDetail: "CURRENT BALANCE",
    color: kBackgroundColorCard,
    iconBgColor: Colors.white,
    icons: Icon(Icons.account_balance),
  ),
  AccountCard(
    accountName: 'Bank',
    amount: "00000",
    borderColor: kMainBoxBorderColor,
    boxShadowColor: kBoxShadowMainBoxBolor,
    cardDetail: "CURRENT BALANCE",
    color: kBackgroundColorCard,
    iconBgColor: Colors.white,
    icons: Icon(Icons.account_balance),
  ),
  AccountCard(
    accountName: 'Esewasssssssssss',
    amount: "00000",
    borderColor: kMainBoxBorderColor,
    boxShadowColor: kBoxShadowMainBoxBolor,
    cardDetail: "CURRENT BALANCE",
    color: kBackgroundColorCard,
    iconBgColor: Colors.white,
    icons: Icon(Icons.account_balance),
  ),
  AccountCard(
    accountName: 'Khalti',
    amount: "00000",
    borderColor: kMainBoxBorderColor,
    boxShadowColor: kBoxShadowMainBoxBolor,
    cardDetail: "CURRENT BALANCE",
    color: kBackgroundColorCard,
    iconBgColor: Colors.white,
    icons: Icon(Icons.account_balance),
  ),
  AccountCard(
    accountName: 'Bank',
    amount: "00000",
    borderColor: kMainBoxBorderColor,
    boxShadowColor: kBoxShadowMainBoxBolor,
    cardDetail: "CURRENT BALANCE",
    color: kBackgroundColorCard,
    iconBgColor: Colors.white,
    icons: Icon(Icons.account_balance),
  ),
  AccountCard(
    accountName: 'Esewasssssssssss',
    amount: "00000",
    borderColor: kMainBoxBorderColor,
    boxShadowColor: kBoxShadowMainBoxBolor,
    cardDetail: "CURRENT BALANCE",
    color: kBackgroundColorCard,
    iconBgColor: Colors.white,
    icons: Icon(Icons.account_balance),
  ),
  AccountCard(
    accountName: 'Khalti',
    amount: "00000",
    borderColor: kMainBoxBorderColor,
    boxShadowColor: kBoxShadowMainBoxBolor,
    cardDetail: "CURRENT BALANCE",
    color: kBackgroundColorCard,
    iconBgColor: Colors.white,
    icons: Icon(Icons.account_balance),
  ),
  AccountCard(
    accountName: 'Bank',
    amount: "00000",
    borderColor: kMainBoxBorderColor,
    boxShadowColor: kBoxShadowMainBoxBolor,
    cardDetail: "CURRENT BALANCE",
    color: kBackgroundColorCard,
    iconBgColor: Colors.white,
    icons: Icon(Icons.account_balance),
  ),
];
