// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
//  await Firebase.initializeApp(
//  options: DefaultFirebaseOptions.currentPlatform,
//  );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLhfZdJTVMNrj6lapjcWfIqr4-7VpjQDA',
    appId: '1:1082766596246:web:015d991da85d34f2e0cab7',
    messagingSenderId: '1082766596246',
    projectId: 'remindwallet',
    authDomain: 'remindwallet.firebaseapp.com',
    storageBucket: 'remindwallet.firebasestorage.app',
    measurementId: 'G-PDT7RFKDK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxZ2oDEIN_tfwcqye59j1JbplqFRGU3-I',
    appId: '1:1082766596246:android:cef142292be46876e0cab7',
    messagingSenderId: '1082766596246',
    projectId: 'remindwallet',
    storageBucket: 'remindwallet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKYWhzAP7uoodfaust-7Y1yt5c9tMGvYU',
    appId: '1:1082766596246:ios:766c8f0d07907209e0cab7',
    messagingSenderId: '1082766596246',
    projectId: 'remindwallet',
    storageBucket: 'remindwallet.firebasestorage.app',
    iosBundleId: 'com.example.remindWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKYWhzAP7uoodfaust-7Y1yt5c9tMGvYU',
    appId: '1:1082766596246:ios:766c8f0d07907209e0cab7',
    messagingSenderId: '1082766596246',
    projectId: 'remindwallet',
    storageBucket: 'remindwallet.firebasestorage.app',
    iosBundleId: 'com.example.remindWallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1soO_v8TrdsgpkuMVtNH6D53bjS0vhqo',
    appId: '1:1082766596246:web:d4ee4020075639fde0cab7',
    messagingSenderId: '1082766596246',
    projectId: 'remindwallet',
    authDomain: 'remindwallet.firebaseapp.com',
    storageBucket: 'remindwallet.firebasestorage.app',
    measurementId: 'G-5K5W45WYDB',
  );

}