// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
//  await Firebase.initializeApp(
//  options: DefaultFirebaseOptions.currentPlatform,
//  );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLhfZdJTVMNrj6lapjcWfIqr4-7VpjQDA',
    appId: '1:1082766596246:web:13536965b10a0534e0cab7',
    messagingSenderId: '1082766596246',
    projectId: 'remindwallet',
    authDomain: 'remindwallet.firebaseapp.com',
    storageBucket: 'remindwallet.appspot.com',
    measurementId: 'G-F0VY1S0ER4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxZ2oDEIN_tfwcqye59j1JbplqFRGU3-I',
    appId: '1:1082766596246:android:0eb67d336076eabce0cab7',
    messagingSenderId: '1082766596246',
    projectId: 'remindwallet',
    storageBucket: 'remindwallet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKYWhzAP7uoodfaust-7Y1yt5c9tMGvYU',
    appId: '1:1082766596246:ios:de869b95f2b31d9ce0cab7',
    messagingSenderId: '1082766596246',
    projectId: 'remindwallet',
    storageBucket: 'remindwallet.appspot.com',
    iosClientId: '1082766596246-d6lhpe918h1f8f0h8587dt85ckhut5ql.apps.googleusercontent.com',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKYWhzAP7uoodfaust-7Y1yt5c9tMGvYU',
    appId: '1:1082766596246:ios:de869b95f2b31d9ce0cab7',
    messagingSenderId: '1082766596246',
    projectId: 'remindwallet',
    storageBucket: 'remindwallet.appspot.com',
    iosClientId: '1082766596246-d6lhpe918h1f8f0h8587dt85ckhut5ql.apps.googleusercontent.com',
    iosBundleId: 'com.example.expensesTracker',
  );
}
